#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorNorth,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     motorEast,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorWest,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     motorSouth,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     shoulder,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     elbow,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "RobotArm.h"

const int THRESHOLD = 15;

float dTheta = PI/4;  // Set forwards on the joystick to the direction of the arm

void rotateAtPower(int rotatePower);

task main()
{
	waitForStart();
	PlaySound(soundBeepBeep);
	initEncoders();

	while (true)
	{
		getJoystickSettings(joystick);

		int xJoy = 0;
    int yJoy = 0;
    int rotatePower = 0;

    if (abs(joystick.joy1_x1) > THRESHOLD)
      xJoy = joystick.joy1_x1 * 100 / 128.0;
    if (abs(joystick.joy1_y1) > THRESHOLD)
      yJoy = joystick.joy1_y1 * 100 / 128.0;
    float theta = 0;
    if (xJoy == 0)
      theta = (yJoy > 0 ? PI/2 : 3*PI/2);
    else
      theta = atan((float)yJoy/xJoy);
    if (xJoy < 0)
      theta += PI;

    float magnitude = sqrt(pow(xJoy,2) + pow(yJoy,2));
    theta += dTheta;

    int xPower = magnitude * cos(theta);
    int yPower = magnitude * sin(theta);

    if (abs(joystick.joy1_x2) > THRESHOLD)
      rotatePower = joystick.joy1_x2 * 100 / 128.0;

    if (rotatePower == 0)
    {
      motor[motorWest] = yPower;
      motor[motorEast] = yPower;
      motor[motorNorth] = xPower;
      motor[motorSouth] = xPower;
    }
    else
    {
      rotateAtPower(-rotatePower);
    }

		setMotorPowersForXY();
		if (joy2Btn(1))
			targetX += .05;
		else if (joy2Btn(3))
			targetX -= .05;

		if (joy2Btn(4))
			targetY += .05;
		else if (joy2Btn(2))
			targetY -= .05;

		if (joystick.joy2_TopHat == 0)
			targetY = H_TIER_3;
		else if (joystick.joy2_TopHat == 2)
			targetY = H_TIER_2;
		else if (joystick.joy2_TopHat == 4)
			targetY = H_TIER_1;
	}
}

void rotateAtPower(int rotatePower)
{
  motor[motorWest] = rotatePower;
  motor[motorEast] = -rotatePower;
  motor[motorNorth] = rotatePower;
  motor[motorSouth] = -rotatePower;
}
