#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     shoulder,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     elbow,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     motorJ,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     wrist,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "RobotArm.h"

bool wristBtnPressed = false;

task main()
{
	waitForStart();
	init();

	while (true)
	{
		getJoystickSettings(joystick);

		setMotorPowersForXY();
		if (joy1Btn(1))
			targetX += .05;
		else if (joy1Btn(3))
			targetX -= .05;

		if (joy1Btn(4))
			targetY += .05;
		else if (joy1Btn(2))
			targetY -= .05;

		if (joy1Btn(6) && !wristBtnPressed)
		{
			wristBtnPressed = true;
			gripperAt90 = !gripperAt90;
		}
		else if (!joy1Btn(6))
			wristBtnPressed = false;

		if (joystick.joy1_TopHat == 0)
			targetY = H_TIER_3;
		else if (joystick.joy1_TopHat == 2)
			targetY = H_TIER_2;
		else if (joystick.joy1_TopHat == 4)
			targetY = H_TIER_1;
	}
}
