#pragma config(Sensor, S1, HTIRS2, sensorI2CCustom)
#pragma config(Sensor, S2,     HTSMUX,     sensorLowSpeed)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     shoulder,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     elbow,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_1,     motorNorth,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorEast,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorWest,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     motorSouth,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C3_1,     motorJ,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     wrist,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "rdpartyrobotcdr-3.1/drivers/hitechnic-irseeker-v2.h"
#include "rdpartyrobotcdr-3.1/drivers/hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.1/drivers/lego-ultrasound.h"
#include "rdpartyrobotcdr-3.1/drivers/lego-light.h"
#include "rdpartyrobotcdr-3.1/drivers/hitechnic-compass.h"

const tMUXSensor ULTRASONIC = msensor_S2_1;
const tMUXSensor LIGHT = msensor_S2_4;
const tMUXSensor COMPASS = msensor_S2_3;

const int THRESHOLD = 15;

bool wristBtnPressed = false;
bool fingerButtonPressed = false;

float dTheta = PI/4;  // Set forwards on the joystick to the direction of the arm

void rotateAtPower(int rotatePower);

task main()
{
	waitForStart();
	HTMCsetTarget(COMPASS);
	PlaySound(soundBeepBeep);

	while (true)
	{
		getJoystickSettings(joystick);

		int dir = HTIRS2readACDir(HTIRS2);
		writeDebugStreamLine("dist: %3d   dir: %2d   compass: %3d",USreadDist(ULTRASONIC), dir, HTMCreadRelativeHeading(COMPASS));

		int xJoy = 0;
    int yJoy = 0;
    int rotatePower = 0;

    if (abs(joystick.joy1_x1) > THRESHOLD)
      xJoy = joystick.joy1_x1 * 100 / 128.0;
    if (abs(joystick.joy1_y1) > THRESHOLD)
      yJoy = joystick.joy1_y1 * 100 / 128.0;
    float theta = 0;
    if (xJoy == 0)
      theta = (yJoy > 0 ? PI/2 : 3*PI/2);
    else
      theta = atan((float)yJoy/xJoy);
    if (xJoy < 0)
      theta += PI;

    float magnitude = sqrt(pow(xJoy,2) + pow(yJoy,2));
    theta += dTheta;

    int xPower = magnitude * cos(theta);
    int yPower = magnitude * sin(theta);

    if (abs(joystick.joy1_x2) > THRESHOLD)
      rotatePower = joystick.joy1_x2 * 100 / 128.0;

    if (rotatePower == 0)
    {
      motor[motorWest] = yPower;
      motor[motorEast] = yPower;
      motor[motorNorth] = -xPower;
      motor[motorSouth] = -xPower;
    }
    else
    {
      rotateAtPower(rotatePower);
    }
	}
}

void rotateAtPower(int rotatePower)
{
  motor[motorWest] = -rotatePower;
  motor[motorEast] = rotatePower;
  motor[motorNorth] = rotatePower;
  motor[motorSouth] = -rotatePower;
}
