#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     shoulder,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     elbow,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main
{
  while (true)
  {
    getJoystickSettings(joystick);

    int elbowPower = 0;
    int shoulderPower = 0;

    if (abs(joystick.joy1_y2)>20)
      elbowPower = joystick.joy1_y2 / 4;

    if (abs(joystick.joy1_y1)>20)
      shoulderPower = joystick.joy1_y1 / 4;

    motor[elbow] = elbowPower;
    motor[shoulder] = shoulderPower;
  }
}
