#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S3,     lightSensor,                    sensorLightActive)
#pragma config(Sensor, S4,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LiftMotor1,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     LiftMotor2,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     LeftDrive,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     BackWheel,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     ArmRaise,      tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

int initialValue;
#define LIGHT_THRESHOLD 5
int ticks = 0;
#define TICKS_THRESHOLD 5

void initializeRobot()
{
  servo[servo1] = 202;
  servo[servo2] = 109;
  motor[ArmRaise] = 10;
  initialValue = SensorValue[lightSensor];
  return;
}

task main()
{
  waitForStart(); // Wait for the beginning of autonomous phase.
  initializeRobot();

  motor[LeftDrive] = 20;
  motor[RightDrive] = 20;
  while (true)
  {
    writeDebugStreamLine("LS: %d", SensorValue[lightSensor]);
    wait10Msec(10);
    if (abs(initialValue - SensorValue[lightSensor]) >= LIGHT_THRESHOLD)
      ticks++;
    else
      ticks = 0;
    if (ticks >= TICKS_THRESHOLD)
      break;
  }
  motor[LeftDrive] = 0;
  motor[RightDrive] = 0;
  motor[BackWheel] = 80;
  PlaySound(soundBeepBeep);
  while (true) {
    wait1Msec(800);
    motor[RightDrive] = -20;
    motor[LeftDrive] = 20;
    motor[BackWheel] = 0;
    wait1Msec(300);
    motor[RightDrive] = 0;
    motor[LeftDrive] = 0;
    motor[BackWheel] = 80;
  }
}
