#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C4  261.63
#define As5 466.16
#define C5  523.25
#define Cs5 554.37
#define D5  587.33
#define Ds5 622.25
#define E5  659.26
#define F5  698.46
#define G5  783.99
#define Gs5 830.61
#define As6 932.33
#define rest 0

bool flipped = false;
int mid = 128;
int diff = 30;

void pt(float freq, int time)
{
  if (freq != 0)
    PlayTone(freq, time);
  wait10Msec(time);
  wait1Msec(10);
  if (freq == 0)
    return;
  //if (flipped)
  //  servo[flag] = mid - diff;
  //else
  //  servo[flag] = mid + diff;
  flipped = !flipped;
}

task main()
{
  motor[motorD] = 100;
  motor[motorE] = 100;
  while (true)
  {

  pt(Ds5,30);
  pt(Ds5,15);
  pt(D5,15);
  pt(rest,15);
  pt(D5,15);
  pt(Ds5,90);
  pt(D5,30);

  pt(Ds5,30);
  pt(Ds5,15);
  pt(D5,15);
  pt(rest,15);
  pt(D5,15);
  pt(Ds5,90);
  pt(D5,30);

  pt(Ds5,15);
  pt(D5,30);
  pt(Ds5,15);
  pt(rest,15);

  pt(D5,30);
  pt(F5,15);
  pt(rest,15);
  pt(F5,15);
  pt(Ds5,30);
  pt(D5,30);
  pt(As5,30);

  pt(C5, 90);
  pt(D5, 30);
  pt(Ds5, 15);
  pt(F5,45);
  pt(G5,60);
  pt(F5,30);
  pt(As6,60);

  pt(Gs5,30);
  pt(G5,15);
  pt(Gs5,45);

  pt(D5,45);
  pt(Ds5,45);
  pt(F5,30);

  wait1Msec(5000);
  }
}
