#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     compass,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorWest,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorNorth,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorEast,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorSouth,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S2_C3_1,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define C4  261.63
#define As5 466.16
#define C5  523.25
#define Cs5 554.37
#define D5  587.33
#define Ds5 622.25
#define E5  659.26
#define F5  698.46
#define G5  783.99
#define Gs5 830.61
#define As6 932.33
#define rest 0

bool flipped = false;
int mid = 128;
int diff = 30;

bool guileRunning = false;

void pt(float freq, int time)
{
  if (freq != 0)
    PlayTone(freq, time);
  wait10Msec(time);
  wait1Msec(10);
  if (freq == 0)
    return;
  if (flipped)
    servo[flag] = mid - diff;
  else
    servo[flag] = mid + diff;
  flipped = !flipped;
}

task guile()
{
  guileRunning = true;
  pt(Ds5,30);
  pt(Ds5,15);
  pt(D5,15);
  pt(rest,15);
  pt(D5,15);
  pt(Ds5,90);
  pt(D5,30);

  pt(Ds5,30);
  pt(Ds5,15);
  pt(D5,15);
  pt(rest,15);
  pt(D5,15);
  pt(Ds5,90);
  pt(D5,30);

  pt(Ds5,15);
  pt(D5,30);
  pt(Ds5,15);
  pt(rest,15);

  pt(D5,30);
  pt(F5,15);
  pt(rest,15);
  pt(F5,15);
  pt(Ds5,30);
  pt(D5,30);
  pt(As5,30);

  pt(C5, 90);
  pt(D5, 30);
  pt(Ds5, 15);
  pt(F5,45);
  pt(G5,60);
  pt(F5,30);
  pt(As6,60);

  pt(Gs5,30);
  pt(G5,15);
  pt(Gs5,45);

  pt(D5,45);
  pt(Ds5,45);
  pt(F5,30);
  guileRunning = false;
}
