#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S4,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LiftMotor1,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     LiftMotor2,    tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     LeftDrive,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  nMotorEncoder[LiftMotor1] = 0;
  nMotorEncoder[LiftMotor2] = 0;
  motor[LiftMotor1] = -10;
  motor[LiftMotor2] = 10;
  while (true)
  {
    writeDebugStreamLine("Motor1 Encoder: %d", nMotorEncoder[LiftMotor1]);
    writeDebugStreamLine("Motor2 Encoder: %d", nMotorEncoder[LiftMotor2]);
    writeDebugStreamLine("");
    wait10Msec(1);
  }
}
