#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     sensorTouch,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     rightArm,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftArm,       tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    rightWing,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    rightArm,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    leftWing,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    leftArm,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    flag,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  nMotorEncoder[leftArm] = 0;
  nMotorEncoder[rightArm] = 0;
  while (true)
  {
    writeDebugStreamLine("LeftArm Encoder: %d", nMotorEncoder[leftArm]);
    writeDebugStreamLine("RightArm Encoder: %d", nMotorEncoder[rightArm]);
    nxtDisplayTextLine(1,"LA Encoder: %d", nMotorEncoder[leftArm]);
    nxtDisplayTextLine(1,"RA Encoder: %d", nMotorEncoder[rightArm]);
    writeDebugStreamLine("");
    wait10Msec(1);
  }
}
