#pragma config(Sensor, S2,     touch,               sensorTouch)
#pragma config(Sensor, S3,     light,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  motor[motorA] = 50;
  bFloatDuringInactiveMotorPWM = true;
  while (true){
    if (SensorValue[touch] == 1)
    {
      motor[motorA] = 50;
      motor[motorB] = 50;
    }
    else
    {
      motor[motorA] =0;
      motor[motorB]=0;
    }
    wait10Msec(10);
    nxtDisplayTextLine(1, "LS: %d", SensorValue[light]);
  }
}
