#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     compass,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rSholder,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLift,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rbCollector,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     lSholder,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     lDrive,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rDrive,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    rFinger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    lFinger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    rWrist,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    lWrist,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_5,    rElbow,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_6,    lElbow,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-v2.4/drivers/HTMC-driver.h"

task main()
{
  int currentHeading = HTMCreadHeading(compass);
  int originalHeading = HTMCreadHeading(compass);
  int nTurns = 0;
  int nTurnsNeeded = 0;
  int targetL = originalHeading - 88;
  if (targetL < 0)
  {
    targetL += 360;
    nTurnsNeeded = 1;
  }
  int targetR = originalHeading + 90;
  if (targetR > 359)
  {
    targetR -= 360;
    nTurnsNeeded = 1;
  }
  writeDebugStreamLine("Heading:\t%d",currentHeading);
  writeDebugStreamLine("targetL:\t%d",targetL);
  wait1Msec(1000);
  motor[rDrive] = -40;
  motor[lDrive] = 40;

  while ((currentHeading > targetL) && (nTurns != nTurnsNeeded || nTurnsNeeded == 0))
  {
    if (abs(HTMCreadHeading(compass) - currentHeading) > 20)
      nTurns++;
    currentHeading = HTMCreadHeading(compass);
    //currentHeading = HTMCreadRelativeHeading(compass);
    writeDebugStreamLine("Heading:\t%d",currentHeading);
    writeDebugStreamLine("targetL:\t%d",targetL);
    nxtDisplayCenteredTextLine(0,"Heading:\t%d",currentHeading);
  }
}
