#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rSholder,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLift,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     rbCollector,   tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     lSholder,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     lDrive,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rDrive,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    rFinger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    lFinger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    rWrist,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    lWrist,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_5,    rElbow,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_6,    lElbow,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOYSTICK_THRESHOLD 15
#define SHOLDER_MAX_POWER  60
#define SHOLDER_REST_POWER 0
#define ELBOW_MAX_POWER    128
#define ELBOW_REST_POWER   127
#define WRIST_MAX_POWER    28
#define WRIST_REST_POWER   127
#define CHAIN_POWER        50
#define SWEEPER_MAX_POWER  100

#define RIGHT_FINGER_MIN   170
#define RIGHT_FINGER_MAX   255
#define LEFT_FINGER_MIN    0
#define LEFT_FINGER_MAX    85

void operateArms();
void operateDrive();

#define PULSE_POWER 10
#define DUTY_CYCLE 1
long lastPulse = 0;
bool pulseOn = false;

void initializeRobot()
{
  servo[rFinger] = 255;
  servo[lFinger] = 0;
  servo[lWrist] = WRIST_REST_POWER;
  servo[rWrist] = WRIST_REST_POWER;
  servo[lElbow] = ELBOW_REST_POWER;
  servo[rElbow] = ELBOW_REST_POWER;
  servoChangeRate[rFinger] = 2;
  servoChangeRate[lFinger] = 2;
  return;
}
task main()
{
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
    getJoystickSettings(joystick);
    //pulseMotors();
    operateArms();
    operateDrive();

    if ((joy1Btn(10) || joy2Btn(10)) && !bSoundActive)
      PlaySoundFile("pirateHQ.rso");
    if (joy1Btn(9) && !bSoundActive)
      PlaySoundFile("NOOOOOO.rso");
    if (joy2Btn(9) && !bSoundActive)
      PlaySoundFile("BeAMan.rso");
  }
}

void moveLeftServo(int dTheta, bool check)
{
  servo[lFinger] += dTheta;
  if (servo[lFinger] < LEFT_FINGER_MIN && check)
    servo[lFinger] = LEFT_FINGER_MIN;
  if (servo[lFinger] > LEFT_FINGER_MAX && check)
    servo[lFinger] = LEFT_FINGER_MAX;
}

void moveRightServo(int dTheta, bool check)
{
  servo[rFinger] -= dTheta;
  if (servo[rFinger] < RIGHT_FINGER_MIN && check)
    servo[rFinger] = RIGHT_FINGER_MIN;
  if (servo[rFinger] > RIGHT_FINGER_MAX && check)
    servo[rFinger] = RIGHT_FINGER_MAX;
}

void operateArms()
{
    int deltaFingers = 0;
    int deltaL = 0;
    int deltaR = 0;
    int rElbowPower = ELBOW_REST_POWER;
    int lElbowPower = ELBOW_REST_POWER;
    int rWristPower = WRIST_REST_POWER;
    int lWristPower = WRIST_REST_POWER;
    int rSholderPower = SHOLDER_REST_POWER;
    int lSholderPower = SHOLDER_REST_POWER;
    int liftPower = 0;
    int sweeperPower = 0;

    if (abs(joystick.joy1_y1) > JOYSTICK_THRESHOLD)
      lSholderPower = joystick.joy1_y1 * SHOLDER_MAX_POWER / 128.0;
    if (abs(joystick.joy1_y1) > JOYSTICK_THRESHOLD)
      rSholderPower = joystick.joy1_y1 * SHOLDER_MAX_POWER / 128.0;


    if (joy2Btn(8))
    {
      // Sweeper pickup
      sweeperPower = -SWEEPER_MAX_POWER;
    }
    else if (joy2Btn(6))
    {
      // Sweeper reverse
      sweeperPower = SWEEPER_MAX_POWER;
    }

    if (joy1Btn(4))
    {
      lElbowPower += ELBOW_MAX_POWER;
      rElbowPower += ELBOW_MAX_POWER;
    }
    else if (joy1Btn(2))
    {
      lElbowPower -= ELBOW_MAX_POWER;
      rElbowPower -= ELBOW_MAX_POWER;
    }

    if (joy1Btn(8))
    {
      lWristPower += WRIST_MAX_POWER;
      rWristPower += WRIST_MAX_POWER;
    }
    else if (joy1Btn(6))
    {
      lWristPower -= WRIST_MAX_POWER;
      rWristPower -= WRIST_MAX_POWER;
    }

    if (joy1Btn(5))
    {
      liftPower = CHAIN_POWER;
    }
    else if (joy1Btn(7))
    {
      liftPower = -CHAIN_POWER;
    }

    if (joy1Btn(1))
    {
      moveLeftServo(1,true);
      moveRightServo(1,true);
    }
    else if (joy1Btn(3))
    {
      moveLeftServo(-1,true);
      moveRightServo(-1,true);
    }

    if (joystick.joy1_TopHat == 7 || joystick.joy1_TopHat == 6 || joystick.joy1_TopHat == 5)
    {
      if (joystick.joy1_x2 < -15)
        moveLeftServo(-1,false);
      else if (joystick.joy1_x2 > 15)
        moveLeftServo(1,false);
    }
    else if (joystick.joy1_TopHat == 1 || joystick.joy1_TopHat == 2 || joystick.joy1_TopHat == 3)
    {
      if (joystick.joy1_x2 < -15)
        moveRightServo(1,false);
      else if (joystick.joy1_x2 > 15)
        moveRightServo(-1,false);
    }

    if (joystick.joy1_TopHat == 1)
      moveRightServo(1,false);
    else if (joystick.joy1_TopHat == 3)
      moveRightServo(-1,false);

    servo[lElbow] = 255-lElbowPower;
    servo[rElbow] = rElbowPower;
    servo[lWrist] = lWristPower;
    servo[rWrist] = 255-rWristPower;

    //writeDebugStreamLine("lEP:\t%d\nrEP:\t%d\nlWP:\t%d\nrWP:\t%d\n",-lElbowPower,rElbowPower,lWristPower,-rWristPower);

    /*servo[lFinger] += deltaFingers + deltaL;
    servo[rFinger] -= deltaFingers + deltaR;*/

    motor[motorLift] = liftPower;
    motor[rSholder] = rSholderPower;
    motor[lSholder] = lSholderPower;
    motor[rbCollector] = sweeperPower;
}

void operateDrive()
{
  int lDrivePower = 0;
  int rDrivePower = 0;

  if (abs(joystick.joy2_y1) > JOYSTICK_THRESHOLD)
    lDrivePower = joystick.joy2_y1 * 100 / 128.0;
  if (abs(joystick.joy2_y2) > JOYSTICK_THRESHOLD)
    rDrivePower = joystick.joy2_y2 * 100 / 128.0;

  motor[lDrive] = lDrivePower;
  motor[rDrive] = rDrivePower;
}

/*void pulseMotors()
{
  long dT = nPgmTime - lastPulse;
  if (pulseOn)
  {
    if (dT > 10*DUTY_CYCLE)
    {
      pulseOn = !pulseOn;
      servo[lElbow] = ELBOW_REST_POWER;
      servo[rElbow] = ELBOW_REST_POWER;
    }
  }
  else
  {
    if (dT > 1000-10*DUTY_CYCLE)
    {
      pulseOn = !pulseOn;
      servo[lElbow] -= PULSE_POWER;
      servo[rElbow] += PULSE_POWER;
    }
  }
}*/
