#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S4,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorD,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while (true)
  {
    motor[motorD] = 100;
    motor[motorE] = 100;
  }
}
