#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S4_C1_1,    lGrip,                tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    rGrip,                tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"	 //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{
  servo[lGrip] = 129;
  servo[rGrip] = 129;
  return;
}

task main()
{
  initializeRobot();

  waitForStart();

  while (true)
  {
    getJoystickSettings(joystick);
    servo[lGrip] = joystick.joy1_y2+129;
    servo[rGrip] = joystick.joy1_y1+129;
    writeDebugStreamLine("%d",servo[lGrip]);
    //motor[rDrive] = joystick.joy1_y2 / 128.0 * 100;
    //motor[lDrive] = joystick.joy1_y1 / 128.0 * 100;
  }
}
