#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     ultrasonic,     sensorSONAR)
#pragma config(Motor,  mtr_S4_C1_1,     motorNorth,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     motorEast,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorWest,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     motorSouth,    tmotorNormal, openLoop)
//#pragma config(Sensor, S3,     compass,        sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//#include "Guile.c"
//#include "Victory.c"
//#include "rdpartyrobotcdr-v2.4/drivers/HTMC-driver.h"
const int THRESHOLD = 15;

const int R_FINGER_MIN = 165;
const int R_FINGER_MAX = 255;
const int L_FINGER_MIN = 90;
const int L_FINGER_MAX = 0;
int delay = 100;

float dTheta = PI/4;  // Set forwards on the joystick to the direction of the arm

void rotateAtPower(int rotatePower);
//void operateArm();

task main()
{
  //HTMCsetTarget(compass,0);

  waitForStart();   // wait for start of tele-op phase

  //HTMCstartCal(compass);

  int lastUltra = 0;
  while (true)
  {
    getJoystickSettings(joystick);
    if (SensorValue[ultrasonic] != lastUltra)
      writeDebugStreamLine("US: %d", SensorValue[ultrasonic]);
    lastUltra = SensorValue[ultrasonic];
    /*if (joy1Btn(6))
    {
      HTMCstopCal(compass);
      break;
    }*/

    int xJoy = 0;
    int yJoy = 0;
    int rotatePower = 0;

    if (abs(joystick.joy1_x1) > THRESHOLD)
      xJoy = joystick.joy1_x1 * 100 / 128.0;
    if (abs(joystick.joy1_y1) > THRESHOLD)
      yJoy = joystick.joy1_y1 * 100 / 128.0;
    float theta = 0;
    if (xJoy == 0)
      theta = (yJoy > 0 ? PI/2 : 3*PI/2);
    else
      theta = atan((float)yJoy/xJoy);
    if (xJoy < 0)
      theta += PI;

    float magnitude = sqrt(pow(xJoy,2) + pow(yJoy,2)) * sqrt(2);
    //float heading = HTMCreadRelativeHeading(compass);
    //writeDebugStreamLine("heading: %f", heading);
    //theta += (PI*(float)heading) / 180.0;
    theta += dTheta;

    int xPower = magnitude * cos(theta);
    int yPower = magnitude * sin(theta);

    if (abs(joystick.joy1_x2) > THRESHOLD)
      rotatePower = joystick.joy1_x2 * 100 / 128.0;

    if (rotatePower == 0)
    {
      motor[motorWest] = yPower;
      motor[motorEast] = yPower;
      motor[motorNorth] = xPower;
      motor[motorSouth] = xPower;
    }
    else
    {
      rotateAtPower(-rotatePower);
    }

    //if (joystick.joy1_TopHat != -1)
    //  dTheta = joystick.joy1_TopHat*PI/4;

    //operateArm();

    if (joy1Btn(10) && !bSoundActive)
      PlaySoundFile("pirateHQ.rso");
    if (joy1Btn(9))
    {
      PlayImmediateTone(random(3000),delay/4);
    }

    if (joy2Btn(10) && !bSoundActive)
      PlaySoundFile("NOOOOOO.rso");
    if (joy2Btn(9) && !bSoundActive)
      PlaySoundFile("getiton.rso");
  }
}

void rotateAtPower(int rotatePower)
{
  motor[motorWest] = rotatePower;
  motor[motorEast] = -rotatePower;
  motor[motorNorth] = rotatePower;
  motor[motorSouth] = -rotatePower;
}

/*bool fingerTriggerPressed = false;
void operateArm()
{
  servo[servo1] = -joystick.joy2_y1 + 127;

  if (joy2Btn(6) && !fingerTriggerPressed)
  {
    fingerTriggerPressed = true;
    if (servo[servo2] == R_FINGER_MAX)
    {
      servo[servo2] = R_FINGER_MIN;
      servo[servo3] = L_FINGER_MIN;
    }
    else
    {
      servo[servo2] = R_FINGER_MAX;
      servo[servo3] = L_FINGER_MAX;
    }
  }
  else if (!joy2Btn(6))
  {
    fingerTriggerPressed = false;
  }

  int shoulderPower = 0;
  int elbowPower = 0;

  if (joystick.joy2_y2 > THRESHOLD)
  {
    elbowPower = (joystick.joy2_y2*35)/128;
  }
  else if (joystick.joy2_y2 < -THRESHOLD)
  {
    elbowPower = (joystick.joy2_y2*50)/128;
  }

  if (joystick.joy2_TopHat == 4)
    shoulderPower = 40;
  else if (joystick.joy2_TopHat == 0)
    shoulderPower = -50;

  if (joy2Btn(8))
  {
    shoulderPower *= 2;
    elbowPower *= 2;
  }

  motor[elbow] = elbowPower;
  motor[shoulder] = shoulderPower;
}*/
