#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    lFinger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rFinger,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"	 //Include file to "handle" the Bluetooth messages.

#define larger(x,y) (x>y)?x:y
#define smaller(x,y) (x<y)?x:y

void initializeRobot()
{
  servo[lFinger] = 0;
  servo[rFinger] = 255;
  return;
}

task main()
{
  initializeRobot();

  waitForStart();

  while (true)
  {
    getJoystickSettings(joystick);
    int lFingerValue = servo[lFinger];
    int rFingerValue = servo[rFinger];
    if (joy1Btn(1))
    {
      lFingerValue++;
      rFingerValue--;
    }
    else if (joy1Btn(3))
    {
      lFingerValue--;
      rFingerValue++;
    }
    lFingerValue = smaller(255,lFingerValue);
    lFingerValue = larger(0,lFingerValue);
    rFingerValue = smaller(255,rFingerValue);
    rFingerValue = larger(0,rFingerValue);
    servo[lFinger] = lFingerValue;
    servo[rFinger] = rFingerValue;
    wait1Msec(1);
  }
}
