#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S4,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    armRaise,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    armRaise2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while (true){
  servo[armRaise] = 130;
  servo[armRaise2] = 50;}
  // armRaise at 180 is up
  /*while (true)
  {
    //servo[armRaise] = 180;
    //servo[armRaise2] = 0;
    //writeDebugStreamLine("Servo1: %d", ServoValue[armRaise]);
    //wait10Msec(500);
    servo[armRaise] = 0;
    servo[armRaise2] = 180;
    //writeDebugStreamLine("Servo1: %d", ServoValue[armRaise]);
    //wait10Msec(500);
  }*/
  //servo[armRaise] = 90;
  //wait10Msec(100);
}
