#pragma config(Sensor, S3,     sSONAR,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while (true)
  {
    nxtDisplayCenteredTextLine(2,"SNR:%d",SensorValue[sSONAR]);
  }
}
