#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S2,     ultrasonic,     sensorSONAR)
#pragma config(Sensor, S3,     compass,        sensorI2CCustom)
#pragma config(Motor,  mtr_S4_C1_1,     motorNorth,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     motorEast,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorWest,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     motorSouth,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     shoulder,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     elbow,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-v2.4/drivers/HTMC-driver.h"
#include "JoystickDriver.c"

// These are radians
const int FORWARDS = PI;
const int RIGHT = PI/2;
const int BACKWARDS = 0;
const int LEFT = -PI/2;

const int R_FINGER_MIN = 165;
const int R_FINGER_MAX = 255;
const int L_FINGER_MIN = 90;
const int L_FINGER_MAX = 0;

// HTMC readings are in degrees. Yay!
const int TURN_TOWARDS_BOARD = 45;

const int DRIVE_FROM_CORNER_TIME = 2400;
const int DISTANCE_FROM_CENTER_RACK = 70;

void setVelocityVector(float magnitude, float theta)
{
  theta -= PI/4; // Make the arm be forwards
  int xPower = magnitude * cos(theta);
  int yPower = magnitude * sin(theta);
  motor[motorWest] = yPower;
  motor[motorEast] = yPower;
  motor[motorNorth] = xPower;
  motor[motorSouth] = xPower;
}

void rotateAtPower(int rotatePower)
{
  motor[motorWest] = rotatePower;
  motor[motorEast] = -rotatePower;
  motor[motorNorth] = rotatePower;
  motor[motorSouth] = -rotatePower;
}

void stopMotors()
{
  motor[motorWest] = 0;
  motor[motorEast] = 0;
  motor[motorNorth] = 0;
  motor[motorSouth] = 0;
}

task main()
{
  waitForStart();
  setVelocityVector(100,BACKWARDS);
  wait1Msec(5500);
  stopMotors();
  /*HTMCsetTarget(compass);
  int filteredUltrasonic = 0;
  while (filteredUltrasonic > 200 && filteredUltrasonic != 255)
  {
    writeDebugStreamLine("%d",filteredUltrasonic);
    filteredUltrasonic = 0;
    for (int i = 0; i < 9; i++)
      filteredUltrasonic += SensorValue[ultrasonic];
    filteredUltrasonic /= 9;
    setVelocityVector(90,FORWARDS);
  }
  stopMotors();*/
}
