#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     sSONAR,         sensorSONAR)
#pragma config(Sensor, S4,     sWallSONOR,     sensorSONAR)
#pragma config(Motor,  motorA,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          ,              tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightArm,      tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftArm,       tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     rightDrive,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     leftDrive,     tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    rightWing,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    leftWing,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    flag,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "MotorControl.h"
#include "JoystickDriver.c"

#define WALL_THRESHOLD 37

task main()
{
  waitForStart();
  while (SensorValue[sSONAR] > WALL_THRESHOLD)
  {
    setLeftDrive(100);
    setRightDrive(100);
  }
  stopDrive();
}
