#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S4,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LiftMotor1,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     LiftMotor2,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     LeftDrive,     tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define LIFT_POWER 20
#define TURBO_LIFT_POWER 40
int currentLiftPower = LIFT_POWER;

bool buttonTurboPressed = false;

int armRaiseAngle = 90;
int armOpenAngle = 90;

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  return;
}

void operateLift()
{
  int lift1Pwr = 0;
    int lift2Pwr = 0;

    if (joy1Btn(3) && !buttonTurboPressed)
    {
      buttonTurboPressed = true;
      if (currentLiftPower == LIFT_POWER)
        currentLiftPower = TURBO_LIFT_POWER;
      else
        currentLiftPower = LIFT_POWER;
    }
    else if (!joy1Btn(3))
    {
      buttonTurboPressed = false;
    }
    if (joy1Btn(4))
      currentLiftPower = 100;
    if (joy1Btn(2))
    {
      lift1Pwr = currentLiftPower;
      lift2Pwr = -currentLiftPower;
    }
    else if (joy1Btn(1))
    {
      lift1Pwr = -currentLiftPower;
      lift2Pwr = currentLiftPower;
    }

    if (joy1Btn(6))
      lift1Pwr = -currentLiftPower;
    else if (joy1Btn(8))
      lift1Pwr = currentLiftPower;

    if (joy1Btn(5))
      lift2Pwr = currentLiftPower;
    else if (joy1Btn(7))
      lift2Pwr = -currentLiftPower;

    motor[LiftMotor1] = lift1Pwr;
    motor[LiftMotor2] = lift2Pwr;
}

void operateArm()
{
  //servo[armRaiseServo] = armRaiseAngle;
  //servo[armOpenServo] = armOpenAngle;
}

void operateWheels()
{
  int leftDrivePower;
  int rightDrivePower;
  if (abs(joystick.joy2_y1) < 5)
    leftDrivePower = 0;
  else
    leftDrivePower = (int)((float)joystick.joy2_y1*100.0/128.0);
  if (abs(joystick.joy2_y2) < 5)
    rightDrivePower = 0;
  else
    rightDrivePower = (int)((float)joystick.joy2_y2*100.0/128.0);

  motor[LeftDrive] = leftDrivePower;
  motor[RightDrive] = rightDrivePower;
}

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
    getJoystickSettings(joystick);
    operateLift();
    operateWheels();
  }
}
