#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S4,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LiftMotor1,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     LiftMotor2,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     LeftDrive,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     BackWheel,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorI,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define LIFT_POWER 20
#define TURBO_LIFT_POWER 40

#define USE_TURN_MODIFIERS

int currentLiftPower = LIFT_POWER;

bool buttonTurboPressed = false;
bool soundKeyPressed = false;

//int armRaiseAngle = 90;
//int armOpenAngle = 90;

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  return;
}

void operateLift()
{
  int lift1Pwr = 0;
    int lift2Pwr = 0;

    if (joy1Btn(3) && !buttonTurboPressed)
    {
      buttonTurboPressed = true;
      if (currentLiftPower == LIFT_POWER)
        currentLiftPower = TURBO_LIFT_POWER;
      else
        currentLiftPower = LIFT_POWER;
    }
    else if (!joy1Btn(3))
    {
      buttonTurboPressed = false;
    }
    if (joy1Btn(4))
      currentLiftPower = 100;
    if (joy1Btn(2))
    {
      lift1Pwr = currentLiftPower;
      lift2Pwr = -currentLiftPower;
    }
    else if (joy1Btn(1))
    {
      lift1Pwr = -currentLiftPower;
      lift2Pwr = currentLiftPower;
    }

    if (joy1Btn(6))
      lift1Pwr = -currentLiftPower;
    else if (joy1Btn(8))
      lift1Pwr = currentLiftPower;

    if (joy1Btn(5))
      lift2Pwr = currentLiftPower;
    else if (joy1Btn(7))
      lift2Pwr = -currentLiftPower;

    motor[LiftMotor1] = lift1Pwr;
    motor[LiftMotor2] = lift2Pwr;
}

void operateArm()
{
  //servo[armRaiseServo] = armRaiseAngle;
  //servo[armOpenServo] = armOpenAngle;
}

void operateWheels()
{
  int drivePower;
  int rotatePower = 0;
  int backWheelPower = 0;
  float leftTurnMultiplier = 1;
  float rightTurnMultiplier = 1;

  // Set power for left and right drive (currently identical)
  if (abs(joystick.joy2_y1) < 10)
    drivePower = 0;
  else
    drivePower = (int)((float)joystick.joy2_y1*100.0/128.0);

    // Set power for back omniwheel
  if (joy2Btn(6))
    backWheelPower = 50;
  if (joy2Btn(8))
    backWheelPower = 100;
  if (joy2Btn(5))
    backWheelPower = -50;
  if (joy2Btn(7))
    backWheelPower = -100;

  if (joystick.joy2_x1 > 10)
  {
    rightTurnMultiplier = 1.0 - (1.0/128.0*joystick.joy2_x1);
  }
  if (joystick.joy2_x1 < -10)
  {
    leftTurnMultiplier = 1.0 + (1.0 / 128.0 * joystick.joy2_x1);
  }
  writeDebugStreamLine("LTM:%f, RTM:%f, j:%d", leftTurnMultiplier, rightTurnMultiplier, joystick.joy2_x1);

  // If right joystick is moved left or right, override all other commands
  // Turn robot in place in the direction indicated by this joystick
  // With power proportional to the x-value
  if (abs(joystick.joy2_x2) > 15)
    rotatePower = (int)((float)joystick.joy2_x2*100.0/128.0);

#ifdef USE_DRIVE_MODIFIERS
    motor[LeftDrive] = drivePower * leftTurnMultiplier;
    motor[RightDrive] = drivePower * rightTurnMultiplier;
#endif
#ifndef USE_DRIVE_MODIFIERS
    motor[LeftDrive] = drivePower;
    motor[RightDrive] = drivePower;
#endif
  motor[BackWheel] = backWheelPower;
  if (rotatePower != 0)
  {
    motor[LeftDrive] = rotatePower;
    motor[RightDrive] = -rotatePower;
    motor[BackWheel] = -rotatePower;
  }
}

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
    getJoystickSettings(joystick);
    operateLift();
    operateWheels();
    operateArm();
    if (joy1Btn(10) && !soundKeyPressed && !bSoundActive)
    {
      soundKeyPressed = true;
      PlaySoundFile("newgq.rso");
    }
    else if (!joy1Btn(10))
      soundKeyPressed = false;
  }
}
